# Yarn 2 configuration file (see https://yarnpkg.com/configuration/yarnrc)

# Disable global cache to enable local git zero-installs (see https://yarnpkg.com/features/caching#zero-installs)
enableGlobalCache: false

# Validates lockfile content matches the remote manifests
enableHardenedMode: true

# Disables `postinstall` scripts from third-party packages
enableScripts: false

# Disables Yarn telemetry
enableTelemetry: false

# Use the Plug'n'Play resolver
nodeLinker: pnp

# Publish packages to the GitHub Package Registry
npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
